### ISSUE TITLE
Can't melt Items

### ISSUE THREAD

**Issue by LettyR** [IamLation/lation_mining#1]
Hi ^^
I do all the dependencies & install from the order.
 I can Pickaxe, but not smelting. I instantly keep getting the "You do not have enough'" - Message, doesn´s matter how much of which Item i have. 
There are no Error codes in F8 or Konsole to share -  what going wrong here ?

**Comment by bylickilabs** [comment]
@LettyR 
Hi, the pickaxe is not intended for smelting, it is only used to mine all the raw materials in the mine. All raw materials that can be mined can be melted down.

**Comment by IamLation** [comment]
v2 is pending release, closing this!
