### ISSUE TITLE
error when I have to melt (qb-target)

### ISSUE THREAD

**Issue by Sellerboy01** [IamLation/lation_mining#4]
I get an error message when I have to melt https://i.gyazo.com/3858f018823b68f4766001ac4ec4afeb.png
Inside qb-target, client.lua I don't know what to do, I'm partly new so could need help with this https://i.gyazo.com/c4191b1abb1f0522355daf45bac4dab2.png

**Comment by IamLation** [comment]
Hey, there's some issues in the current version. I am currently in the process of rewriting this for v2!

**Comment by Sellerboy01** [comment]
@IamLation It is fine, thanks for the quick reply

**Comment by IamLation** [comment]
v2 is pending release, closing this!
