### ISSUE TITLE
pickaxe wont work need help plz

### ISSUE THREAD

**Issue by Kryptixdior** [IamLation/lation_mining#5]
says pick axe isnt in great condition but it was just brought??? any help 
![Uploading image_2024-12-29_124444407.png…]()

**Comment by IamLation** [comment]
What framework and inventory are you on?

**Comment by Kryptixdior** [comment]
qb-core framework and qb-inventory atm

**Comment by IamLation** [comment]
> qb-core framework and qb-inventory atm

And I assume you've properly read the config and setup your pickaxe metadata correctly as mentioned in the comment on line 110 in config/shared.lua?

```
-- metadata: optional metadata for item
-- metadata: ⚠️ use 'durability' if using ox_inventory, otherwise use 'quality'
[1] = { item = 'ls_pickaxe', price = 150, icon = 'hammer', metadata = { ['durability'] = 100 }, level = 1 },
```

If you are not using ox_inventory, you must update the metadata key from durability to quality, as described. Have you done that?

**Comment by Kryptixdior** [comment]
worked thank you

**Comment by IamLation** [comment]
You're welcome
