### ISSUE TITLE
Ore syncing between players

### ISSUE THREAD

**Issue by tkMaukingbird** [IamLation/lation_mining#6]
When more than one player is mining at the same time, the ore prop destruction is not synced for other players in the area. The ore still appears intact and they can still mine that prop using target, but they do not receive a reward item when the progress bar is complete.

**Comment by IamLation** [comment]
> When more than one player is mining at the same time, the ore prop destruction is not synced for other players in the area. The ore still appears intact and they can still mine that prop using target, but they do not receive a reward item when the progress bar is complete.

Thanks for the report. The ores not being synced is by designed, giving everyone a chance to mine the same sections at their own pace. However other players should be able to mine the ore and receive the reward. I will fix that.

**Comment by tkMaukingbird** [comment]
Thanks for the quick response. This makes sense to me. I appreciate your help!

**Comment by IamLation** [comment]
> Thanks for the quick response. This makes sense to me. I appreciate your help!

You're welcome! Resolved & closed <3
